name: Build turnip Debug for Dev Every weeks

on:
  workflow_dispatch:

jobs:
  build_turnip:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install deps
      run: |
        sudo apt-get install -y ninja-build ccache
        sudo pip install meson
    
    - name: Run build script
      run: bash ./turnip_builder_debug.sh 
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: Turnip magisk module
        tag_name: workflow_${{github.run_number}}
        name: Release ${{github.run_number}}
        files: |
           turnip_workdir/turnipXiaomiPocoModdebug.zip
#          turnip_workdir/meson_log
#          turnip_workdir/ninja_log
