name: Build All

permissions: write-all

on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 1,8,15,22 * *"

jobs:
  build_turnip:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install deps
      run: |
        sudo apt-get install -y ninja-build ccache glslang-tools libdrm-dev libdrm2
        sudo pip install meson
        sudo cp -a depend/deps /opt/deps
    
    - name: Run build scripts
      run: |
        bash ./turnip_builder.sh
        bash ./turnip_builder_gl.sh
        bash ./mali_turnip.sh 
      
    - name: Release Mesa Turnip Latest
      uses: softprops/action-gh-release@v1
      with:
        body: Freedreno, Turnip and Mali Latest
        tag_name: workflow_${{github.run_number}}
        name: Release ${{github.run_number}}
        files: |
           workdir/turnipVK.zip
           workdir/FreedrenoGL.zip
           workdir/panfrostmali.zip
           workdir/vulkan.adreno.so
           workdir/libEGL_adreno.so
           workdir/libGLESv1_CM_adreno.so
           workdir/libGLESv2_adreno.so
           workdir/libvulkan_panfrost.so