name: Build turnip

on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 1,8,15,22 * *"

jobs:
  build_turnip:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install deps
      run: |
        sudo apt-get install -y ninja-build ccache glslang-tools libdrm-dev libdrm2 libdrm-freedreno1
        sudo pip install meson
    
    - name: Run build scripts
      run: |
        bash ./turnip_builder.sh
        bash ./turnip_builder_gl.sh 
      
    - name: Release Mesa Turnip Latest
      uses: softprops/action-gh-release@v1
      with:
        body: Turnip magisk module Latest
        tag_name: workflow_${{github.run_number}}
        name: Release ${{github.run_number}}
        files: |
           turnip_workdir/turnipVK.zip
           turnip_workdir/vulkan.adreno.so
           turnip_workdir_gl/FreedrenoGL.zip
           turnip_workdir_gl/libEGL_adreno.so
           turnip_workdir_gl/libGLESv1_CM_adreno.so
           turnip_workdir_gl/libGLESv2_adreno.so
#          turnip_workdir/meson_log
#          turnip_workdir/ninja_log
